[package]
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
description = "Fetch and show tldr help pages for many CLI commands. Full featured offline client with caching support."
homepage = "https://github.com/dbrgn/tealdeer/"
license = "MIT/Apache-2.0"
name = "tealdeer"
readme = "README.md"
repository = "https://github.com/dbrgn/tealdeer/"
version = "0.4.0"

[[bin]]
name = "tldr"
path = "src/main.rs"

[dependencies]
ansi_term = "0.10.2"
clippy = { version = "0.0.174", optional = true }
curl = "0.4.8"
docopt = "0.8.1"
env_logger = { version = "0.4.3", optional = true }
flate2 = "0.2.20"
log = "0.3.8"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"
tar = "0.4.14"
time = "0.1.38"
walkdir = "2.0.1"
xdg = "2.1.0"

[dev-dependencies]
tempdir = "^0.3"
assert_cli = "^0.5"

[features]
dev = ["clippy"]
logging = ["env_logger"]
